In [1]:
import pandas as pd

In [40]:
pd.set_option('display.max_colwidth', None)
#pd.reset_option('display.max_colwidth')

In [63]:
episodes = pd.read_csv('../data/episodes_with_id.csv')
episodes_filtered = episodes[episodes['numMainSpeakers'] == 3]
episodes_filtered
episodes_filtered[['epTitle', 'mp3url','episode_id']].head(50)

,epTitle,mp3url,episode_id
0,Bringing Back Our Sense of Community,https://anchor.fm/s/11abe148/podcast/play/15344549/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-17%2F83194249-44100-2-bc23c65d66c68.mp3,1
3,OWR 203,https://anchor.fm/s/126c0978/podcast/play/15840996/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-07-21%2Fccb7a609626d52cfe97eebc50d050859.m4a,4
21,"Daily Readings Only - Tuesday June 2, 2020 Blackout Tuesday",https://feeds.soundcloud.com/stream/832836613-ddornerjr-daily-readings-only-tuesday.mp3,22
34,What is 'Real' Christianity?,https://anchor.fm/s/fc0c4ac/podcast/play/14947756/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-9%2F80799873-32000-1-349c8436f3b94.mp3,35
37,Cung Le exposes UFC & Family Law courts,https://anchor.fm/s/2558474/podcast/play/14609920/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-12-14%2F616c589d7785dc429b8c3e913720b2df.m4a,38
39,246) William Defebaugh: Exploring the intricate balance between the flourishing and decay of life,https://podcasts.captivate.fm/media/885509ef-e1b8-47ed-971c-239dc0615202/246-exploring-the-intricate-balance-between-the-flourishing-and.mp3,40
43,S1 Ep8: Appropriation in a Global Food World,https://chrt.fm/track/8B7A46/traffic.megaphone.fm/PODS5540178173.mp3?updated=1668598911,44
50,"PSP Let's Talk: Yohannes Berhane, Jake Wenstrup",https://anchor.fm/s/1f999408/podcast/play/14603033/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-5-1%2F78649033-44100-2-417e51e41b09f.m4a,51
76,Black Lives Matter: The View from Ireland,https://www.buzzsprout.com/886948/4360184-black-lives-matter-the-view-from-ireland.mp3,77
83,Medical Students Demand an Anti-Racist Education,https://static1.squarespace.com/static/5e34a702359e3e28ffa093ef/t/5ef03a58e69a0b0f27d517ab/1592802066145/Well+Rounded_Ep+10_Betial+Asmerom.mp3,84
99,"This Sunday's Game: GAA Pride, from Valencia to Dublin",https://feeds.soundcloud.com/stream/819633397-capital-sports-moscow-gaa-pride-valencia-dublin.mp3,100
113,Take A Bold Path with Caeli Quinn / Climate Ride,https://mcdn.podbean.com/mf/web/tjmphu/OBD_5_10_CaeliQuinn.mp3,114
122,Why Ranked Ballots?,https://anchor.fm/s/14e814d0/podcast/play/14952171/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-11%2F513b4827b3e2eda938e55950b5a2c691.m4a,123
134,Do Not Be Afraid,https://t.subsplash.com/r/aHR0cHM6Ly9jZG4uc3Vic3BsYXNoLmNvbS9hdWRpb3MvR01QOTI2LzBlMjIwN2MzLWM1Y2MtNDIxZS1iYTRmLTJiOWNkM2Q5ZmJiZC9hdWRpby5tcDM.mp3?k=GMP926&s=3&sapid=vnnm3vt,135
162,"Let's Have A Conversation, Vol. 2",https://feeds.soundcloud.com/stream/833193055-brunchbreakdown-lets-have-a-conversation-vol-2.mp3,163
218,JLP | Justice Clarence Thomas Went from RAGE to RESPONSIBILITY,https://feeds.soundcloud.com/stream/824009866-jesseleepeterson-jlp-justice-clarence-thomas-went-from-rage-to-responsibility.mp3,219
220,6.21.20,https://anchor.fm/s/462deb0/podcast/play/15440295/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-19%2F7f7a49a4b4816e2a64a40e9ecc912471.m4a,221
221,6.14.20,https://anchor.fm/s/462deb0/podcast/play/15106123/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-12%2Fd0ab4ca8732d09b2198b3488647ec42f.m4a,222
231,S7 Episode 17: Will We Emerge in a Community Mindset? with Dr. Eddie Moore Jr.,https://traffic.libsyn.com/secure/3psinapod/Dr_Eddie_More_2nd_Edit.mp3?dest-id=589817,232
237,Y your Country?,https://anchor.fm/s/17e54a2c/podcast/play/14727751/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-4%2F79422496-16000-2-8ab8a529f6894.mp3,238
253,Unzipping My Feelings,https://anchor.fm/s/1da15870/podcast/play/14603707/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-1%2F78654759-44100-2-ca7439884ab9c.m4a,254
261,The Maiden Voyage,https://anchor.fm/s/22819544/podcast/play/14149698/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-4-22%2F75762908-44100-2-57fff6f0417f3.mp3,262
277,47 - Penny Talks Seriously and Our Interview with Robin Wilt,https://anchor.fm/s/d3f86dc/podcast/play/14757952/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-5%2F79614090-48000-2-b4a125d5ab331.mp3,278
280,LA Riots,https://traffic.megaphone.fm/APO5538450844.mp3,281
310,Ep 252 - The Abolition Suite Vol. 1: #DefundCPD with Asha Ransby-Sporn,https://feeds.soundcloud.com/stream/847546951-airgoradio-ep-252-the-abolition-suite-vol-1-defundcpd-with-asha-ransby-sporn.mp3,311
311,PPE Podiatry | Protect | Evolve,https://api.spreaker.com/download/episode/34162803/june_episode_x_sitmso_online_audio_converter_com.mp3,312
312,'There is Paper Plates' Ep. 30,https://anchor.fm/s/94e911c/podcast/play/13569533/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-05-12%2F979c7952b8ed3e49e9769d1d338f660b.m4a,313
341,Cultivate: Conversations on Race (Part 4: Practical Steps with the Moores),https://www.buzzsprout.com/794990/4363904-cultivate-conversations-on-race-part-4-practical-steps-with-the-moores.mp3,342
353,Be Apart of Change ✊🏾,https://anchor.fm/s/168a783c/podcast/play/15698996/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-25%2F6148b7d396828765c5f78b6dbc5e8a37.m4a,354
359,112. A Jewish Response To Police Brutality,https://www.buzzsprout.com/2109073/11978585-112-a-jewish-response-to-police-brutality.mp3,360
364,The Rebirth of Mothra II Ft. Josh Naughts,https://traffic.libsyn.com/secure/gargantucast/Mothra_2_Final.mp3?dest-id=983711,365
370,How Ray J & Willie Norwood Build Wealth Through Intellectual Property,https://anchor.fm/s/c323b04/podcast/play/15443342/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-26%2F77e580ad1242b47c3460ac501bb020d0.m4a,371
375,iHeartRadio Communities with Ryan Gorman,https://dts.podtrac.com/redirect.mp3/api.spreaker.com/download/episode/30436427/900779_2_ihrcommunities_0613_0614.mp3,376
377,#11 – Eve McCormick on Effective Altruism,https://pinecast.com/listen/15ee3a24-14fb-48d4-8166-9dd0d2744d1e.mp3?source=rss&ext=asset.mp3,378
389,Ep. 67 Donato Clay and Rep. Gene Wu - Challenging Racist Institutions: St. Thomas' Episcopal School,https://traffic.libsyn.com/secure/htownprogressive/ep_67_donato_clay_and_rep_gene_wu.mp3?dest-id=838703,390
396,Boss Lady Coaching Podcast Jerisia Lamons RISE,https://feeds.soundcloud.com/stream/846939289-user-335784936-boss-lady-coaching-podcast-jerisia-lamons-rise.mp3,397
400,At Home With Leaders - Chris Powell,https://media.blubrry.com/leaders_performance_podcast/content.blubrry.com/leaders_performance_podcast/LPP-2020-06-24-086.mp3,401
401,At Home With Leaders - Rick Spielman,https://media.blubrry.com/leaders_performance_podcast/content.blubrry.com/leaders_performance_podcast/LPP-2020-06-12-084.mp3,402
408,Humble Justice Bundle,https://chtbl.com/track/E7177/traffic.megaphone.fm/FPMN4571338491.mp3,409
412,Rene Syler on speaking out against racial injustice | Ep 205,https://traffic.megaphone.fm/CMP5331684136.mp3?updated=1663335976,413
414,"Episode 42: Mauro Icardi to PSG, Premier League Return & Transfer Market Talk!",https://traffic.omny.fm/d/clips/33250137-f269-48a3-86dc-abcd016c932f/61429d23-b42e-4a8b-84f2-ad2d00fc7dd3/26c8d937-820c-4f5e-9d63-ad2d0101d5f5/audio.mp3?utm_source=Podcast&in_playlist=f6b74474-30ee-41bf-ae73-ad2d00fc7de6,415
444,013. COVID-19 Impact on Diverse & Underserved Communities,https://mcdn.podbean.com/mf/web/zmfxea/Diversity_Deep_Dive_013_COVID_19_Impact_on_Diverse_and_Underserved_Communities_MIX.mp3,445
446,THIS TRULY IS... The Current State of BLM on Social Media & Beyond - Ft. Alexandra Nikolajev S2 E6,https://feeds.soundcloud.com/stream/841565890-thistrulyis-this-truly-is-the-current-state-of-blm-on-social-media-beyond-ft-alexandra-nikolajev-s2-e6.mp3,447
463,Misogynoir and Climate Justice,https://traffic.megaphone.fm/GOAL3562780589.mp3,464
468,Media Literacy expert Renee Hobbs,https://api.spreaker.com/download/episode/33317067/cs_live_renee_hobbs.mp3,469
469,'Mediatrician' & Pediatrician Dr. Michael Rich,https://api.spreaker.com/download/episode/31726776/cs_live_michael_rich.mp3,470
473,IMPRVMNT #7 - The Dark Side Of Human Nature - with Lawrence and Darius (Part 1),https://anchor.fm/s/d4c3364/podcast/play/15344856/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-17%2F83196777-44100-2-0424ea52b87bd.m4a,474
489,"Race, Education, and Protest: A Conversation with Hamline University’s President",http://www.podtrac.com/pts/redirect.mp3/feeds.soundcloud.com/stream/840798061-officehours-with-eab-race-education-and-protest-a-conversation-with-hamline-universitys-president.mp3,490
490,136 Bob Williams & Brian Baines - Civil Unrest and the CEO,https://traffic.libsyn.com/secure/leadershipandbusiness/136_-_Leadership_and_Business_-_Williams_and_Baines.mp3?dest-id=298329,491
492,The Book of Titus Part 7,https://mcdn.podbean.com/mf/web/hubr4r/TITUS_Part_7_edited.mp3,493

In [64]:
# paragraph_turns = pd.read_csv('../data/paragraph_turns_with_emotions.csv')
# paragraph_turns[paragraph_turns['episode_id'] == 24].tail(10)

In [71]:
mergedDf = pd.read_csv('../data/speaker_turns.csv')

In [74]:
filtered_df = mergedDf[mergedDf['mp3url'] == 'https://traffic.megaphone.fm/GOAL3562780589.mp3']
filtered_df.head()

Empty DataFrame
Columns: [mfcc1_sma3Mean, mfcc2_sma3Mean, mfcc3_sma3Mean, mfcc4_sma3Mean, F0semitoneFrom27_5Hz_sma3nzMean, F1frequency_sma3nzMean, turnText, speaker, startTime, endTime, duration, mp3url, turnCount, inferredSpeakerRole, inferredSpeakerName]
Index: []

In [62]:
# Assign text colors to speakers
speaker_colors = {
    'SPEAKER_00': '#E66100',  # Red-Orange
    'SPEAKER_01': '#5D3A9B',  # Dodger Blue
    'SPEAKER_00, SPEAKER_01': '#999999',  # Green
    'SPEAKER_01, SPEAKER_00': '#999999',  # Blue-Violet
}

# Build HTML content
html_content = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.5; }
    </style>
</head>
<body>
<p>
"""

for _, row in filtered_df.iterrows():
    color = speaker_colors.get(row['speakers'], '#000000')  # Default black if no match
    html_content += f'<span style="color: {color};">{row["content"]} </span>'

html_content += "</p>\n</body></html>"

# Save to an HTML file
with open("../data/transcript_color.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("HTML file saved as transcript.html")

HTML file saved as transcript.html

In [57]:
mergedDf.rename(columns={
    'mfcc1_sma3Mean': 'mfcc1_sma3',
    'mfcc2_sma3Mean': 'mfcc2_sma3',
    'mfcc3_sma3Mean': 'mfcc3_sma3Mean',
    'mfcc4_sma3Mean': 'mfcc4_sma3Mean',
    'F0semitoneFrom27_5Hz_sma3nzMean': 'F0semitoneFrom27.5Hz_sma3nz',
    'F1frequency_sma3nzMean': 'F1frequency_sma3nz',
    'speaker': 'speakers',
    'startTime': 'start',
    'endTime': 'end',
    'turnText': 'content'
}, inplace=True)

Pick an episode.

In [44]:
def getColoredTranscript(mergedDf): 
    #from colorama import Fore
    #foreColors = [Fore.RED, Fore.GREEN, Fore.YELLOW, Fore.BLUE, Fore.MAGENTA, Fore.CYAN]
    colList = ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#a65628','#f781bf']

    uSpeakers = set([speakerList[0] for speakerList in mergedDf["speakers"] if len(speakerList) > 0])
    numSpeakers = len(uSpeakers) 
    colDict = dict(zip(uSpeakers, colList[:numSpeakers]))
    colDict["NONE"] = "#000000"
    colDict["MULT"] = '#999999'


    #highlight transcript colors 
    pastSpeakList = "NONE"
    currText = ""
    allText = ""

    for i, row in mergedDf.iterrows(): 
        word = row["content"]
        speakList = row["speakers"]

        """ 
        if len(speakers) > 0: 
            speakList = speakers[-1]
        else: 
        """
        if len(speakList) == 0: 
            speakList = ["NONE"]

        if speakList != pastSpeakList: 
            if len(pastSpeakList) > 1: 
                allText += f'<font color = "{colDict["MULT"]}">{currText}</font>'
            else:  
                allText += f'<font color = "{colDict[pastSpeakList[0]]}">{currText}</font>'

            currText = ""

        if word == word and word != None: 
            currText += word
        pastSpeakList = speakList

    return allText

In [45]:
getColoredTranscript(filtered_df)

'<font color = "#999999"></font><font color = "#999999"> Thank you for listening to this episode of Changes Big and Small. This is your host, Damien. Each week I share research or interview guests to help you make changes in your own life. Currently I am focused on a special series exploring equality, justice and anti-racism. Today I am speaking with Brian Summers who lives in New Jersey. Brian Summers has honed his craft as a portrait photographer capturing classical images of guests of the hip hop and culture podcast, The Combat Jack Show. In addition to hosting two of his own weekly photography based podcast, we are getting better and shooting with shooters. Since moving to New York in 2013, Summers has worked on personal photography projects that eventually led to art exhibitions in New York and Washington, DC. After taking the stage at a creative morning\'s New York event, Brian was bitten by the speaking bug. Since then, he has used his experiences in media, fine arts and personal lives to share with audiences. In addition to creating "We\'re Getting Better", Summers has helped educational workshops at universities and agencies about diversity in the media. In 2016, Summers turned his attention to helping to change the negative narrative of black men with the goal of photographing 1,000 men and boys with the We Love You project. The series was installed as a mural in DC as well as online with the Google Cultural Institute. Find more work from Brian, Buyer, the WeLoveYouProject.com and briansummers.com. Welcome, Brian. I\'m happy that you managed to find time to chat with me so quickly.</font><font color = "#999999"> No problem. Like I mentioned in the bio, I started the We Love You project about four years ago and it kind of slowed momentum a little bit. Recently with the current tipping point boiling over everybody having their own uprisings in their different cities, I was kind of hesitant to march the very first time that I had something in me to do something. It wasn\'t the march. It was like, "How do I use my talents?" And the same thing happened again, added and COVID. And I\'m like, "I\'m not going out here." But it was right outside my door. So I had to go and I had to choose a shirt to wear and I was thinking, "Okay, let me just throw on my We Love You shirt." The project is one of those projects where it ended but the work doesn\'t stop. So people are always going to ask you, "When are you going to do that again?" "When is phase two or phase three?" So it was funny that I wore that shirt that day and then immediately afterwards things start to pick up a little bit. So it\'s just funny how it happens.</font><font color = "#999999"> There\'s power in those words, definitely</font><font color = "#999999">.</font><font color = "#999999"> So what was your</font><font color = "#999999"> reluctance</font><font color = "#999999"> with marching? What were you thinking, feeling that you didn\'t want to</font><font color = "#999999"> demonstrate</font><font color = "#999999">? Four years ago when I took the initiative to help bring people together with this photo project, my reluctance then was marching. It\'s not dead but it\'s a thing that it passed. We learned about Martin Luther King and his strategies. And actually we don\'t even learn about the strategies. We learn about Martin Luther King marching. Martin Luther King went to jail because he demonstrated Malcolm X was a little more extreme and he got killed for it. So my learning growing up in school was that. And I think I was listening to Sean King. I recently say something. I\'m going to paraphrase. He said the way that we learn history about these leaders is always conflict, conflict, conflict, conflict. There\'s no rest or how do I deal with my family? And then back then obviously there\'s no internet. It\'s just newspaper. So you\'ve got to strategize on how to get in the paper. So I was thinking this was like an old style of protesting. It\'s still my work but it might take longer. Today we have technology like my cell phone. We know about all of these present day Emmett Tills because of everybody\'s cell phone. But during the time of actual Emmett Tills we only knew about that one nationally because of the press that it got or even Martin Luther King was one of those demonstrations when they were in Alabama I believe. The famous picture that we all know from civil rights history looks like a black young man being attacked by a police dog. But in reading the Malcolm Gladwell book I realized that that was planned. We knew what the racist officers in the racist society was going to do and how they\'re going to react. But when they protested first of all they filled a church. So it was like a safe ground, hologram. Then they invited kids out to this event at this church. It was just a bunch of mess going on in Alabama. It was bait for this community to have a tipping point. And then it spilled over. And then next we know that we got an awesome photo of racism happening with this dog being sicked on this young man. So it\'s a casualty but it\'s a strategy. Or even marching and sitting in. We did that back then so we could fill the jails so that you can\'t send us nowhere else and you have to see us because it\'s powers and numbers. So the people now marching on you prepared to go to jail and fill up the jail because that was a strategy back then and how we moving forward with it today. So I thought for myself from my own perspective how can I contribute if I\'m already hesitant to march. I\'m the only one but I don\'t want to go out and risk getting tear gassed or being another name when I can try to strategize from where I am in my seat. And if that\'s digitally if I can reach people across the world faster than I can in the street then that\'s my calling. And I can aid any black lives matter movement by showing the visuals or showing the people showing the images of the black lives that matter</font><font color = "#999999">. So it sounds to me like you looked at the strategy that was used before and through reading Malcolm Gladwell\'s book and your own thinking you realized that okay this is not just about demonstrating. It\'s also about how do we get the visibility that we need in order to indicate that there is something wrong here and create the change that we</font><font color = "#999999"> want. So</font><font color = "#999999"> the project that you came up with was the We Love You project and that is a project that shows representations of black men with how they can portray themselves because so often when we see a black man who\'s been killed or who\'s going through the courts in the news it\'s the worst image that they could</font><font color = "#999999"> find. Exactly</font><font color = "#999999">. And there\'s something wrong with this person clearly there deserve to be in trouble of some sort.</font><font color = "#999999"> Exactly.</font><font color = "#999999"> And it always gives me pause because I always think these are human beings regardless of whether or not they did something wrong. And I don\'t understand why this is the only perspective that you\'re showing</font><font color = "#999999">.</font><font color = "#999999"> So I really appreciate the project and the work that you\'ve been doing with showing a different perspective. I noticed that everybody wears a black shirt. Is this the We Love You shirt that you then gift participants in the project? Or is</font><font color = "#999999"> that different</font><font color = "#999999">? So the way it initially worked out was we invited people out. It was like a regular digital call to, I want to call it models but it\'s called the people to come take a picture. We used to ask people to come wearing a black t-shirt. Obviously we had to keep refining it because some folks came up with like black seats and shirts</font><font color = "#999999">. So black men shirts. And they</font><font color = "#999999">\'re like, okay, I need a solid black cotton t-shirt. No graphic design on it. But yes, afterwards we gifted them We Love You shirt. But for some cities that we had a chance to go to somebody might not come exactly uniform. It might be a charcoal shirt. And we just say, okay, you can put the shirt on now because I want the design on the shirt wasn\'t that high up. So I won\'t see We Love You. I\'m actually wearing one right now and you can\'t see it because the cameras</font><font color = "#999999"> crop. So how did you decide on the black t-shirt? What will you go in for with the aesthetic of the style that you use for the portraits?</font><font color = "#999999"> Right. So I think black is just subliminal. The whole thing about the portraits really was I wanted people marching together digitally. It\'s like a solidarity. Even though it\'s one photo of you, it\'s you next to 999 other single photos. So I had a chance to actually install a mural in DC at Union Market. They have just a bunch of white buildings, like a campus of buildings, to be honest. But it\'s white buildings and I have black shirts on white backgrounds. That way it\'s all neutral. You can focus on the person\'s face and not necessarily their color or shade of color because everybody was black. But it ranged from the lightest of black people to the darkest of black people to different sizes to different heights and whatnot to different ages. But the black shirt just brought it all together as the uniform, the black shirt match with the white background. It just helped you focus more on the face. It\'s not everybody\'s centered in their photos. You can see them. It\'s who you think they are. I used to live in Brooklyn. And if you\'re familiar with Brooklyn, I used to say in Bed-Stuy. And Brooklyn is split up by different neighborhoods and sections. So I was living with Bed-Stuy and the three streets over was no string avenue. So by gentrification, in every place in the world, it happens. But where I was staying was the part of Brooklyn or part of Bed-Stuy that was already being gentrified. The prices of houses were already going up higher than the rest of Bed-Stuy. And so as you cross over no string avenue, going deeper into Bed-Stuy, you start to see cops patrolling two by two on every other street. Bed-Stuy is a condensed place. So it\'s not far to go to the next street. So it\'s two by two white cops patrolling down this black neighborhood. And I doubted any of these cops lived there. But me going to see one of my friends that lives in an area I would go over and I\'d see these cops all the time. And me, I don\'t know if it\'s me being from the south of that, but I\'m a little more friendly where I might wave more. So I acknowledge people. So when I\'m walking and I see these cops, I say, "How are you doing?" But these cops are doing their job. I don\'t know what their life is like. I don\'t know what\'s going on or what they\'re thinking. But I know they don\'t recognize me because I don\'t live here. But if you see people in the area that you work every day, you should be able to know that, "Okay, this person, even though I have to intervene in a situation or if I don\'t, I just know when this person is walking, they\'re not a suspect. This is David. This is Johnny. This is Keisha. This is Sarah because I see them every day. And I know even if they\'re causing a problem or are the source of something, I can go and deescalate it more effectively because I know them. And if you see these images every day, even if you don\'t see that person, if you see these people that are in this neighborhood every day or somebody that looks like them, maybe you\'ll have a little more humanity or a little more compassionate about this person because they are a person just like you. They have a family to go back to you just like you. So that\'s one of the goals. I think I was able to do that in DC with that mural. But that\'s the tangent reason for why they\'re wearing black shirts just to make it all about just the face. Let</font><font color = "#999999">\'s step back because we kind of got</font><font color = "#999999"> started and I just kind</font><font color = "#999999"> of went with it. So tell us what\'s your work and my work. I don\'t necessarily mean what you\'re paid for</font><font color = "#999999">, but</font><font color = "#999999"> also the thing that you do that you think serves others as well. I\'m</font><font color = "#999999"> an artist. I went to school for design, but I\'ve always been immersed in art ever since I was a kid. So my literal work is I\'m in the media and I\'m a content creator. So it\'s predominantly photography. Previous jobs I produced video content and podcasts, but my work things that have been a calling has been portrait photography and capturing photographs of people. That\'s evolved over the time. I felt like I was preparing for it when I moved to New York in 2013 and I was taking portraits at a podcast called the Combat Jack Show and I was like a weekly thing sometimes twice a week, but every week I was taking portraits and my nine to five I was taking portraits of guests that came through all the time too. So that evolved into me just for finding taking close up shots and really finding the humanity in each person that I take a picture of. So when that first tipping point for me happened with a Philando Caso Freddie Gray and Mike Brown. People for three deaths helped me push towards scaling up those portraits and taking it from celebrities and podcasts guests to everyday people. You might not know who they are because they have on a black shirt whether it\'s a celebrity or an actual cop that might come out in solidarity as</font><font color = "#999999"> well. What is it about portraits that really captivates you? I am not very good at photography, but I have some friends who are really into photography who love portraits as well. What is it about that that captivates</font><font color = "#999999"> you? I think a portrait is something that\'s intimate. We\'re taught, at least in America, we\'re taught like not to stare at people, but you can stare at a photo and you can study a photo. So if there\'s somebody that\'s interested in which everybody is interested in their own way, if I can find something visually about it that I like whether it\'s me a photographer or me the viewer, I think a portrait gives you chance to study somebody just soon possibly what they might have been through or how they got to this point right here. Then you can change up a portrait with the most subtle details even though it\'s just a person\'s face or maybe like shoulders up. So much in somebody\'s expression whether it\'s a smile, a frown, a squint, an accessory they might have on their face, stuff like that, it captivating at me about photography. I never</font><font color = "#999999"> thought about it that way, but as you explain it, that really makes sense because you can make time to really study a portrait and think about it and have curiosity in a way that we don\'t always do. It\'s an</font><font color = "#999999"> invitation I</font><font color = "#999999"> guess to be curious as well. So after this group of three who were killed by the police, you decided to do the Will of View project.</font><font color = "#999999"> I think I</font><font color = "#999999"> read you went to four cities, is that right</font><font color = "#999999">? Yes, I started in Brooklyn, went from Brooklyn to DC, because I\'m originally from the area,</font><font color = "#999999"> so it was</font><font color = "#999999"> easy just go back home. So it was Brooklyn, DC, Philly. I went to, I did a test in Norfolk with a few of my friends and their family. So I guess the total is Norfolk, DC, Philly, Baltimore, and I had a chance to go out to San Jose to work with Google. So the internal, the black Googlers, the employees of Google, they called me out and we had a chance to take photos of the black workers of Google at that particular campus for one day. It was a handful. It was one of those things where the goal of the project was to break the internet. And I think if there\'s a company to partner with to break the internet, it\'s probably Google. Definitely</font><font color = "#999999">. Yeah. I</font><font color = "#999999"> love the</font><font color = "#999999"> work that you\'ve been doing there. I\'ve been sharing it with all my friends and saying, check this out. Is it great looking at all of these photos of all these different shades of black? It\'s self selection, right? So people kind of being in control in some way of how they\'re being portrayed. What have you learned from doing this project</font><font color = "#999999">? One of the things that I\'ve learned is I guess it\'s the message. It just reinforced that what I assumed it was obviously where we all might joke about all races possibly looking alike. But that\'s one of those ignorant jokes. But you can\'t deny it. We\'re all brown. We\'re all brown to a certain degree, right? We might have similar hairstyles, but we\'re very different. And I learned that every time I took a photo of somebody, we might have photographed 100 people in a day in some cities. I think I did 200 in DC in a day. But that means I have five minutes for everybody to just break the ice. If that I ask them, how you\'re doing? How do you hear about the project? Make sure you come out. The majority of the answers were, hey, my wife told me about it. My girlfriend brought me out or my daughter told me about it. So again, it\'s reinforcing that women are the saviors and looking out for us as always. And then I guess everyone is definitely different. I had a chance to photograph people on the west coast and the east coast, people that I have no idea where they are visiting from. It\'s like there was a young man that I photographed who was the son of one of the black Googlers. And I say son, but I would assume son because that\'s what he looked like to me. His dad worked for Google, but his mom was there with him. And the mom mentioned that their son was about to reveal himself. So he was going through a transition. I can\'t say that he was trans or queer or what the word that he might want to identify with is, but the person was wearing lipstick and they had a cowry shell in the middle of the forehead. I lived in New York for a while, so I\'m kind of used to seeing quote unquote people that might come off weird. But in that moment, it\'s like I can\'t be the one judging anybody because I\'m just taking your photo. I\'m giving you the platform to take back your image. And this young person was about to transition. And that was a big deal for them. It\'s just like compared to a sweet 16 or whatever you want to call it, but that\'s a turn point in their life and they\'re going through this. So now that wasn\'t the first time that somebody that was, I don\'t want to say is more or less different, but they\'re different even when it comes to what I asked for. I asked for black people to come out and you might think that that\'s narrow, but that\'s still super broad. So this black person in this category or however you want to label it came out because they identify with overall being black and whether they\'re black trans or young black and old, black from San Francisco, black from DC. It\'s a very large range and that\'s only United States. I guess it\'s like that iceberg photo. We all love to reference the tip at iceberg is whatever the issue is, but under the water, it\'s so much. So the tip of it is what we look like on our side, but the iceberg in the water is everything that you don\'t know until you actually get to know that</font><font color = "#999999"> person. That\'s interesting because in some ways we get used to judging people based on their photos. And even when we might think that we\'re taking back our image, people are still going to draw certain conclusions from what they see. So there\

In [46]:
def save_transcript_as_html(transcript, filename="../data/transcript_color.html"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write("<html><body>" + transcript + "</body></html>")
    print(f"Transcript saved as {filename}")

html_transcript = getColoredTranscript(filtered_df)
save_transcript_as_html(html_transcript)

Transcript saved as ../data/transcript_color.html