In [1]:
import pandas as pd

In [ ]:
#pd.set_option('display.max_colwidth', None)
#pd.reset_option('display.max_colwidth')

In [2]:
paragraph_turns = pd.read_csv('../data/paragraph_turns_with_emotions.csv')

In [4]:
# Calculate the total count and NaN count of 'speaker' for each episode_id
episode_counts = paragraph_turns.groupby('episode_id')['speaker'].apply(lambda x: x.isna().sum() / len(x))

# Get the episode_ids where less than half of the rows have speaker as NaN
valid_episode_ids = episode_counts[episode_counts < 0.10].index

# Filter the paragraph_turns DataFrame
filtered_paragraph_turns = paragraph_turns[paragraph_turns['episode_id'].isin(valid_episode_ids)]

In [5]:
episodes = pd.read_csv('../data/episodes_with_id.csv')
episodes = episodes[episodes['episode_id'].isin(filtered_paragraph_turns['episode_id'])]
len(episodes)

38

In [6]:
mergedDf = pd.read_csv('../data/10ksample_speakerturn_full.csv')
mergedDf = mergedDf.merge(episodes[['mp3url', 'episode_id']], on='mp3url', how='left')
mergedDf = mergedDf.dropna(subset=['episode_id'])
mergedDf['sentence_count'] = mergedDf['turnText'].str.count(r'[.!?]') + 1
mergedDf['sentence_count'] = mergedDf['sentence_count'].fillna(0).astype(int)
mergedDf['sentence_count'].describe()

count    862.000000
mean       5.733179
std       21.979418
min        0.000000
25%        1.000000
50%        1.000000
75%        3.000000
max      277.000000
Name: sentence_count, dtype: float64

In [7]:
episodes['episode_id']

188        189
606        607
721        722
1578      1579
1927      1928
2538      2539
2592      2593
3224      3225
3226      3227
3259      3260
3418      3419
3664      3665
3965      3966
3989      3990
4050      4051
4117      4118
4740      4741
4983      4984
5055      5056
5505      5506
5526      5527
5611      5612
5646      5647
6828      6829
7251      7252
7576      7577
7656      7657
7959      7960
7971      7972
8009      8010
8117      8118
8290      8291
8653      8654
8862      8863
9023      9024
9032      9033
9547      9548
10430    10431
Name: episode_id, dtype: int64

In [114]:
mergedDf[mergedDf['episode_id'] == 10431].head(10) #7252

,mfcc1_sma3Mean,mfcc2_sma3Mean,mfcc3_sma3Mean,mfcc4_sma3Mean,F0semitoneFrom27_5Hz_sma3nzMean,F1frequency_sma3nzMean,turnText,speaker,startTime,endTime,...,multiAction,multiActionLLM,mainEpSpeakers,newSpeaker,newMainEpSpeakers,totalSpLabels,numNewMainEpSpeakers,racialJustice,episode_id,sentence_count
540353,24.718210,5.234679,4.561526,-11.812523,24.894012,639.943569,"Hey, it's Nicola, just in and there have been...",SPEAKER_01,0.00,53.33,...,NaN,NaN,"SPEAKER_00, SPEAKER_01",SPEAKER_01,"['SPEAKER_00', 'SPEAKER_01']",2.0,2,NaN,10431.0,7
540354,7.687579,2.691753,-0.779907,-4.730061,11.813502,662.612882,protests,"SPEAKER_01, SPEAKER_00",53.33,54.12,...,NaN,NaN,"SPEAKER_00, SPEAKER_01",SPEAKER_01,"['SPEAKER_00', 'SPEAKER_01']",2.0,2,NaN,10431.0,1
540355,21.646099,10.185203,17.199412,7.947550,13.109868,518.573998,. It's a wait and see approach. We're certainl...,SPEAKER_00,54.12,68.52,...,NaN,NaN,"SPEAKER_00, SPEAKER_01",SPEAKER_00,"['SPEAKER_00', 'SPEAKER_01']",2.0,2,NaN,10431.0,7
540356,20.679629,12.840901,-9.879081,-7.090428,15.817565,649.747568,Last,"SPEAKER_00, SPEAKER_01",68.52,68.88,...,NaN,NaN,"SPEAKER_00, SPEAKER_01",SPEAKER_00,"['SPEAKER_00', 'SPEAKER_01']",2.0,2,NaN,10431.0,1
540357,23.390069,3.317431,3.859591,-13.787220,24.320000,641.231508,"Thursday, a crowd of close to 800 people gath...",SPEAKER_01,68.88,94.64,...,NaN,NaN,"SPEAKER_00, SPEAKER_01",SPEAKER_01,"['SPEAKER_00', 'SPEAKER_01']",2.0,2,NaN,10431.0,4

In [115]:
paragraph_turns[paragraph_turns['episode_id'] == 10431].head(50)

,sentence,collectiveAction,racialJustice,collectiveActionMulti,episode_id,sentence_length,speaker,newSpeaker,mfcc1_sma3Mean,mfcc2_sma3Mean,...,curiosity,fear,disapproval,nervousness,disgust,disappointment,anger,grief,remorse,embarrassment
28165,"Hey, it's Nicola, just in and there have been ...",0,1,3.0,10431,22,SPEAKER_01,SPEAKER_01,24.718210,5.234679,...,0.002330,0.003570,0.006853,0.001778,0.001766,0.007500,0.000885,0.000648,0.000558,0.001035
28166,Deputy Chief Medical Officer Paul Callie says ...,1,0,NaN,10431,22,"SPEAKER_01, SPEAKER_00",SPEAKER_01,7.687579,2.691753,...,0.014517,0.001389,0.018117,0.001203,0.001025,0.009986,0.000614,0.000407,0.001044,0.000729
28167,It's a wait and see approach. We're certainly ...,1,0,NaN,10431,6,SPEAKER_00,SPEAKER_00,21.646099,10.185203,...,0.001785,0.008588,0.005661,0.001481,0.000858,0.001963,0.001101,0.000342,0.000460,0.000355
28168,"Last Thursday, a crowd of close to 800 people ...",1,0,NaN,10431,18,"SPEAKER_00, SPEAKER_01",SPEAKER_00,20.679629,12.840901,...,0.001571,0.000764,0.003987,0.001143,0.001471,0.011160,0.000784,0.000587,0.000602,0.001338
28169,"At Australia Zoo, we'll receive a $3 million s...",1,0,NaN,10431,27,SPEAKER_01,SPEAKER_01,23.390069,3.317431,...,0.000706,0.000935,0.002790,0.000881,0.000828,0.004941,0.000758,0.000564,0.000863,0.000461

In [109]:
filtered_df = mergedDf[mergedDf['episode_id'] == 9548]
filtered_df.columns

Index(['mfcc1_sma3Mean', 'mfcc2_sma3Mean', 'mfcc3_sma3Mean', 'mfcc4_sma3Mean',
       'F0semitoneFrom27_5Hz_sma3nzMean', 'F1frequency_sma3nzMean', 'turnText',
       'speaker', 'startTime', 'endTime', 'duration', 'mp3url', 'turnCount',
       'inferredSpeakerRole', 'inferredSpeakerName', 'predictedClassIndex',
       'binaryAction', 'multiAction', 'multiActionLLM', 'mainEpSpeakers',
       'newSpeaker', 'newMainEpSpeakers', 'totalSpLabels',
       'numNewMainEpSpeakers', 'racialJustice', 'episode_id',
       'sentence_count'],
      dtype='object')

In [110]:
# Assign text colors to speakers
speaker_colors = {
    'SPEAKER_00': '#E66100',  # Red-Orange
    'SPEAKER_01': '#5D3A9B',  # Dodger Blue
    'SPEAKER_00, SPEAKER_01': '#999999',  # Green
    'SPEAKER_01, SPEAKER_00': '#999999',  # Blue-Violet
}

# Build HTML content
html_content = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.5; }
    </style>
</head>
<body>
<p>
"""

for _, row in filtered_df.iterrows():
    color = speaker_colors.get(row['speaker'], '#000000')  # Default black if no match
    html_content += f'<span style="color: {color};">{row["turnText"]} </span>'

html_content += "</p>\n</body></html>"

# Save to an HTML file
with open("../data/transcript_speakerturn_color.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("HTML file saved as transcript.html")

HTML file saved as transcript.html

In [112]:
filtered_df = paragraph_turns[paragraph_turns['episode_id'] == 9548]
filtered_df.columns

Index(['sentence', 'collectiveAction', 'racialJustice',
       'collectiveActionMulti', 'episode_id', 'sentence_length', 'speaker',
       'newSpeaker', 'mfcc1_sma3Mean', 'mfcc2_sma3Mean', 'mfcc3_sma3Mean',
       'mfcc4_sma3Mean', 'F0semitoneFrom27_5Hz_sma3nzMean',
       'F1frequency_sma3nzMean', 'startTime', 'endTime', 'duration',
       'turnCount', 'streak', 'streak_length', 'gratitude', 'excitement',
       'joy', 'neutral', 'approval', 'admiration', 'relief', 'caring',
       'optimism', 'realization', 'surprise', 'pride', 'desire', 'love',
       'annoyance', 'amusement', 'confusion', 'sadness', 'curiosity', 'fear',
       'disapproval', 'nervousness', 'disgust', 'disappointment', 'anger',
       'grief', 'remorse', 'embarrassment'],
      dtype='object')

In [113]:
# Assign text colors to speakers
speaker_colors = {
    'SPEAKER_00': '#E66100',  # Red-Orange
    'SPEAKER_01': '#5D3A9B',  # Dodger Blue
    'SPEAKER_00, SPEAKER_01': '#999999',  # Green
    'SPEAKER_01, SPEAKER_00': '#999999',  # Blue-Violet
}

# Build HTML content
html_content = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transcript</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.5; }
    </style>
</head>
<body>
<p>
"""

for _, row in filtered_df.iterrows():
    color = speaker_colors.get(row['newSpeaker'], '#000000')  # Default black if no match
    html_content += f'<span style="color: {color};">{row["sentence"]} </span>'

html_content += "</p>\n</body></html>"

# Save to an HTML file
with open("../data/transcript_paragraphturn_color.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("HTML file saved as transcript.html")

HTML file saved as transcript.html